<?php

/** @var \Magebrew\ImageUploadFormField\ViewModel\BannerViewModel $viewModel */
$viewModel = $block->getData('viewModel');

$bannerImageUrl = $viewModel->getBannerImageUrl();
$bannerImageTablet = $viewModel->getBannerImageTabletUrl();
$bannerImageMobile = $viewModel->getBannerImageMobileUrl();
?>

<?php if ($bannerImageUrl): ?>
    <picture>
        <source class="h-full w-full object-cover"
                srcset="<?= (string)$bannerImageMobile ?>"
                media="(max-width: 375px)"
        >
        <source class="h-full w-full object-cover"
                srcset="<?= (string)$bannerImageTablet ?>"
                media="(max-width: 768px)"
        >
        <source class="h-full w-full object-cover"
                srcset="<?= (string)$bannerImageUrl ?>"
                media="(min-width: 768px)"
        >
        <img class="h-full w-full object-cover"
             src="<?= (string)$bannerImageUrl ?>"
             alt="PVC Pipes, Valves, Fittings and More!"
             loading="lazy"
        >
    </picture>

<?php endif; ?>
